# Generated by Django 5.2.16 on 2026-07-27 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_roomamenity_room_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='hotels.hotel'),
        ),
    ]
