# Generated by Django 5.2.16 on 2026-08-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_thumbnail_alter_hotelimage_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='hotel',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
